### ISSUE TITLE
place unit test classes to the corresponding package in test

### ISSUE THREAD

**Issue by vatolinrp** [AliaksandrFiodarau3/MediaServer#11]
if your class is located at main/java/com/epam/service/impl, then unit test for this class should be located in corresponding package: test/java/com/epam/service/impl

**Comment by AliaksandrFiodarau3** [comment]
You closed a pull request for this issue. Can you close this issue?

**Comment by AliaksandrFiodarau3** [comment]
https://github.com/AliaksandrFiodarau3/MediaServer/pull/12/commits/8c69598d73976e1fd4ade28f456c5de408053f14
