### ISSUE TITLE
do you really need this jstl dependency in every module?

### ISSUE THREAD

**Issue by vatolinrp** [AliaksandrFiodarau3/MediaServer#18]
https://github.com/AliaksandrFiodarau3/MediaServer/blob/073c3c1cf3c4638d739c66df2d45ddea909b78c4/pom.xml#L45

**Comment by AliaksandrFiodarau3** [comment]
Moved the jstl depenency and the javaEE dependency to web module

**Comment by AliaksandrFiodarau3** [comment]
https://github.com/AliaksandrFiodarau3/MediaServer/pull/28/commits/04a74e007747e349bf77712ab4d3ee4c16024c82
