### ISSUE TITLE
improve package structure

### ISSUE THREAD

**Issue by vatolinrp** [AliaksandrFiodarau3/MediaServer#2]

**Comment by AliaksandrFiodarau3** [comment]
Need to create a modular structure?
![moduls](https://user-images.githubusercontent.com/11583130/36303644-ec5ccd9c-131d-11e8-9e9b-178f188c3acb.jpg)

**Comment by vatolinrp** [comment]
Please, put your classes and test classes into logically correct packages

**Comment by AliaksandrFiodarau3** [comment]
I will try to do this, but I combine the task with the 2 issue. Okay?

**Comment by vatolinrp** [comment]
please don't combine.
