### ISSUE TITLE
why does your dao interface return query? this is really strange

### ISSUE THREAD

**Issue by vatolinrp** [AliaksandrFiodarau3/MediaServer#20]
https://github.com/AliaksandrFiodarau3/MediaServer/blob/073c3c1cf3c4638d739c66df2d45ddea909b78c4/dao/src/main/java/com/epam/mediaserver/dao/ArtistDao.java#L19

**Comment by vatolinrp** [comment]
it does not look good. please explain.

**Comment by AliaksandrFiodarau3** [comment]
These methods need DAO for call SQL query. I can call the only fields with a query. I see it practise in manuals.

**Comment by vatolinrp** [comment]
could you please give me a link to one of these manuals? This doesn't look right. Will you need this method outside DAO ? I guess - not. So what is the reason for exposing it?

**Comment by AliaksandrFiodarau3** [comment]
https://github.com/AliaksandrFiodarau3/MediaServer/pull/29/commits/4bd4549d4d63c6909313cfbc23b0f04749bdb365

**Comment by vatolinrp** [comment]
looks better.
