### ISSUE TITLE
As I see you created custom implementation of Connection. Please move it outside of this class.

### ISSUE THREAD

**Issue by vatolinrp** [AliaksandrFiodarau3/MediaServer#21]
https://github.com/AliaksandrFiodarau3/MediaServer/blob/073c3c1cf3c4638d739c66df2d45ddea909b78c4/dao/src/main/java/com/epam/mediaserver/dao/impl/pool/ConnectionPool.java#L224

**Comment by vatolinrp** [comment]
refactor code if needed.

**Comment by AliaksandrFiodarau3** [comment]
Divided connection poll into two classes
https://github.com/AliaksandrFiodarau3/MediaServer/pull/30/commits/020e07f40028a86b52f67b114a317b3e48f718cf
