### ISSUE TITLE
what is this file for?

### ISSUE THREAD

**Issue by vatolinrp** [AliaksandrFiodarau3/MediaServer#36]
https://github.com/AliaksandrFiodarau3/MediaServer/blob/b45265f6ab865d46833ba095a28b1951e27d71f2/d#L1

**Comment by AliaksandrFiodarau3** [comment]
https://github.com/AliaksandrFiodarau3/MediaServer/pull/37/commits/977b2fad954145a396cbb7acfca0a46cbdc6e04b

**Comment by vatolinrp** [comment]
please specify a commit from master, but not from your development branch

**Comment by AliaksandrFiodarau3** [comment]
64953e02f83cf32465da38aebb3fb383f68d54a1
